### ISSUE TITLE
Missing LICENSE or COPYING

### ISSUE THREAD

**Issue by omouse** [RisingStack/graphql-server#11]
Can we get a license on this, like AGPL or MIT? Thanks, I want to use this at work and modify it but I'm not sure if I have to contribute modifications back or not.

I noticed in the NPM package.json the license is listed as ISC: https://opensource.org/licenses/ISC

**Comment by hekike** [comment]
Hi this was just a tutorial repo, pls use https://github.com/risingstack/graffiti instead.

**Comment by omouse** [comment]
Okay so can I assume that it's under the ISC license and I have permission
to work off of it? That's really what I'm asking here.

Thanks will look at graffiti

**Comment by hekike** [comment]
@omouse yes it is, I'm going to update it soon.

**Comment by hekike** [comment]
@omouse I added an MIT one, https://github.com/RisingStack/graphql-server . Feel free to work with it ;)

**Comment by ghost** [comment]
awesome! thanks :D
