### ISSUE TITLE
Populating associations

### ISSUE THREAD

**Issue by gyzerok** [RisingStack/graphql-server#2]
I'm requesting an addition for populating nested associations.

**Comment by hekike** [comment]
@gyzerok what do you mean under this?
user's friends connection isn't a good example for nesting?

**Comment by gyzerok** [comment]
@hekike I mean JOINS between collections. If you store nested collections not like embed document but as separate collections.

**Comment by gyzerok** [comment]
@hekike Sorry, I'm kinda stupid. Never mind :)
