### ISSUE TITLE
not showing it

### ISSUE THREAD

**Issue by AlfonsoAnaValentina** [RisingStack/graphql-server#4]
As I show on the image below, I can't see the query resutlt, and it's been days since I started with this, and I wanna know if I'm missing something or just having some kind of bugs.
Thanks in advance! 
![issuegraphql](https://cloud.githubusercontent.com/assets/7719401/8734587/577e5d24-2be1-11e5-9786-7cd258c4038f.png)

**Comment by funkytek** [comment]
#5 will resolve this, or create a record in your db with the id referenced in client

**Comment by AlfonsoAnaValentina** [comment]
Thankx!!! It was really really helpful!!!! :D
