### ISSUE TITLE
co-body not supporting application/graphql

### ISSUE THREAD

**Issue by almasakchabayev** [RisingStack/graphql-server#8]
Hello, 

I wanted to say that your example is great and it worked flawlessly for me, however if I use curl instead of superagent I get unsupported content-type: application/graphql. 

I can see that co-body does not support 'application/graphql', but is there a way to make it work with 'application/graphql' header?

Thx

**Comment by hekike** [comment]
@almasakchabayev hi, I think you should create a library/middleware which uses `co-body` or different body parser and you can change content type to something supported. I don't see any program to using `application/json` here.
